users:
  list:
    - {name: 12312312312,pwd: d333b303a4abf7965102d8f03475d71a,isSummary: true}
    - {name: 15280404395,pwd: 96e79218965eb72c92a549dd5a330112,isSummary: true}
attendance:
  serviceUrl: http://nsysapi.lsxjy.com.cn
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    # 方式一：  引用外部文件
    #        url: jdbc:sqlite:D:/eclipse/xy.db
    #方式二： 引用项目中的文件
    #    url: jdbc:sqlite::resource:static/sqlite/attendance.db
    url: jdbc:sqlite:sqlite/attendance.db?date_string_format=yyyy-MM-dd HH:mm:ss
    username:
    password: